#!/bin/bash

#bash script to get other tools and requirements

#cms detector code
wget https://raw.githubusercontent.com/robwillisinfo/cms-detector.py/master/cms-detector.py

#tool for banner; already pre installed, but you can install if needed
apt-get install figlet

#google dorks list
wget https://raw.githubusercontent.com/BullsEye0/google_dork_list/master/google_Dorks.txt

#subdomain enumerating tool
git clone https://github.com/aboul3la/Sublist3r.git

#web application xss scanner
https://github.com/faizann24/XssPy.git
