#!/bin/bash

#bash script to get other tools and requirements

#cms detector code
wget https://raw.githubusercontent.com/robwillisinfo/cms-detector.py/master/cms-detector.py

#tool for banner; already pre installed, but you can install if needed
apt-get install figlet

#google dorks list
wget https://raw.githubusercontent.com/BullsEye0/google_dork_list/master/google_Dorks.txt

#subdomain enumerating tool
git clone https://github.com/aboul3la/Sublist3r.git

#web application xss scanner
git clone https://github.com/faizann24/XssPy.git

#email info gathering tool 
git clone https://github.com/m4ll0k/Infoga.git

#python script to discover hidden endpoints 
git clone https://github.com/GerbenJavado/LinkFinder.git

#recon ans vulnerability scanning suite
git clone https://github.com/s0md3v/Striker.git
